In [1]:
from dotenv import load_dotenv 

load_dotenv() 

True

In [ ]:
from dotenv import load_dotenv 
load_dotenv()
import os 
import openai 
## english text to translate 
english_text ="Hellow , how are you"

response= openai.ChatCompletion.create(
    model= "gpt-"
)

In [6]:
# Prompt for summarization
prompt = "Describe the following movie using emojis. {movie}:"

examples = [
    {"input": "Titanic", "output": "❤"},
    {"input": "The Matrix", "output": "🕶️💊"}
]


In [8]:
prompt.format(movie= examples[0]['input'])

'Describe the following movie using emojis. Titanic:'

In [7]:
import torch
import torch.nn as nn

# 1. Model
class Encoder(nn.Module):
    def __init__(self, vocab_size, embed_size, hidden_size):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_size)
        self.lstm = nn.LSTM(embed_size, hidden_size, batch_first=True)

    def forward(self, input_seq):
        embedded = self.embedding(input_seq)
        _, (hidden, cell) = self.lstm(embedded)
        return hidden, cell

# 2. Tokenize
sentence = "hello my name is ujjwal basnet".split()
vocab = {word: idx for idx, word in enumerate(set(sentence))}
token_ids = [vocab[word] for word in sentence]
input_tensor = torch.tensor([token_ids])  # [1, seq_len]

# 3. Run Encoder
vocab_size = len(vocab)
embed_size = 3
hidden_size = 3

encoder = Encoder(vocab_size, embed_size, hidden_size)
hidden, cell = encoder(input_tensor)

print("Hidden vector:", hidden)


Hidden vector: tensor([[[-0.3172, -0.1366,  0.0658]]], grad_fn=<StackBackward0>)


In [21]:
sentence = "Hi my name is Ujjwal".split()
sentence

['Hi', 'my', 'name', 'is', 'Ujjwal']

In [23]:
vocab= {word: id for id , word in enumerate(set(sentence))}
vocab

{'is': 0, 'my': 1, 'name': 2, 'Hi': 3, 'Ujjwal': 4}

In [24]:
token = [vocab[word] for word in sentence]
token

[3, 1, 2, 0, 4]

In [ ]:
#convert inot tensor
token_id_tensor = torch.tensor(data = token)
token_id_tensor

tensor([3, 1, 2, 0, 4])

In [30]:
vocab_len

5

In [31]:
vocab_len= len(vocab)
embde_size= 8
hidden_state= 4 



In [43]:
embedding = nn.Embedding(num_embeddings= vocab_len , embedding_dim= embde_size)
embedding= embedding(token_id_tensor)

In [45]:
embedding[0]

tensor([ 0.1918, -0.4736,  0.5541, -0.0339, -1.8716,  0.4641, -1.4603, -0.2889],
       grad_fn=<SelectBackward0>)

In [35]:
## CALCULATING SIMILARITIE COSIN 

In [103]:
sentences

[['I', 'love', 'cats'],
 ['I', 'love', 'dogs'],
 ['We', 'love', 'cats'],
 ['We', 'all', 'dogs']]

In [112]:
word2idx = {}
idx2word= {}
idx= 0
for sentence in sentences: 
    for word in sentence:
        if word not in word2idx:
            word2idx[word]= idx
            idx2word[idx]= word 
            idx +=1

In [113]:
for token in ['<PAD>', '<UNK>']:
    if token not in word2idx:
        word2idx[token] = idx
        idx2word[idx] = token
        idx += 1


'dogs'

In [115]:
word2idx.get(word)

3

In [108]:
sentences

[['I', 'love', 'cats'],
 ['I', 'love', 'dogs'],
 ['We', 'love', 'cats'],
 ['We', 'all', 'dogs']]

In [106]:
word2idx

{'I': 0, 'love': 1, 'cats': 2, 'dogs': 3, 'We': 4, 'all': 5}

In [75]:
sentences = [
    ["I", "love", "cats"],
    ["I", "love", "dogs"],
    ["We", "love", "cats"],
    ["We", "all", "dogs"]
]


In [92]:
import numpy as np

In [94]:
aray= np.asarray(sentences)

TypeError: 'module' object is not callable

In [100]:
((aray.flatten()))

array(['I', 'love', 'cats', 'I', 'love', 'dogs', 'We', 'love', 'cats',
       'We', 'all', 'dogs'], dtype='<U4')

In [54]:
cosine_similarity(embedding[0].unsqueeze(0) , embedding[1].unsqueeze(0))

tensor([-0.3595], grad_fn=<SumBackward1>)

In [70]:
similarities = {}
for i in range(len(token)):
    j_list = []  # Initialize j_list inside the outer loop to reset per i
    for j in range(len(token)):
        if j == i:
            continue
        else:
            similarity = cosine_similarity(embedding[i].unsqueeze(0), embedding[j].unsqueeze(0))
            j_list.append(similarity.item())  # Append to j_list, no assignment needed
    similarities[i] = j_list  # Assign list after inner loop completes


In [71]:
## find the embedding of the 
similarities

{0: [-0.3594808280467987,
  0.29179155826568604,
  0.5593845248222351,
  -0.7663167715072632],
 1: [-0.3594808280467987,
  -0.4311680495738983,
  0.3233092427253723,
  0.6723902225494385],
 2: [0.29179155826568604,
  -0.4311680495738983,
  -0.32815033197402954,
  -0.3414401113986969],
 3: [0.5593845248222351,
  0.3233092427253723,
  -0.32815033197402954,
  -0.3987118601799011],
 4: [-0.7663167715072632,
  0.6723902225494385,
  -0.3414401113986969,
  -0.3987118601799011]}

In [73]:
token_id_tensor

tensor([3, 1, 2, 0, 4])

In [74]:
vocab

{'is': 0, 'my': 1, 'name': 2, 'Hi': 3, 'Ujjwal': 4}

In [72]:
sentence

['Hi', 'my', 'name', 'is', 'Ujjwal']